<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INBANGNBLENO10" name="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid" tests="4" failures="0" timestamp="24 Oct 2018 10:23:48 GMT" time="230.670" errors="0">
  <testcase name="Test04ReceiveRetireThenRetireAtSameLocation" time="64.735" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test02ReceiveRetireThenPutawayAtSameLocation" time="54.141" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test01ReceiveRetireThenCycleCountAtSameLocation" time="56.451" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test03ReceiveRetireThenReturnAtSameLocation" time="55.343" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
</testsuite> <!-- com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid -->
