<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBANGNBLENO10" name="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest" tests="22" failures="2" timestamp="23 Oct 2018 20:35:24 GMT" time="183.314" errors="0">
  <testcase name="test10_Th100Ex10Scanned10Unknown10Known" time="9.080" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test11_Th100Ex10Scanned10Known" time="7.896" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test18_Th20Ex10Scanned10Known" time="8.983" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test13_Th100Ex8Scanned10Known" time="7.731" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test06_Th0Ex8Scanned10Known" time="8.848" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test22_Th20Ex9Scanned7Known2Missing" time="8.211" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test20_Th20Ex8Scanned10Known2Extra" time="8.061" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;false&gt; but was:&lt;true&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<false> but was:<true>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest.test20_Th20Ex8Scanned10Known2Extra(ThCalculationNCCNeverTest.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test20_Th20Ex8Scanned10Known2Extra -->
  <testcase name="test16_Th20Ex0Scanned10Known" time="8.028" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test21_Th20Ex10Scanned9Known2Missing1Extra" time="7.736" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test19_Th20Ex10Scanned8KnownEqualsThreshold" time="7.966" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test03_Th0Ex10Scanned10Unknown10Known" time="7.245" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test02_Th0Ex0Scanned10Known" time="10.346" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test08_Th100Ex0ScannedAllUnknown" time="7.463" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test01_Th0Ex0ScannedAllUnknown" time="9.200" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest">
    <failure type="java.lang.AssertionError" message="Failed: Threshold met status expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Failed: Threshold met status expected:<true> but was:<false>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
at com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest.test01_Th0Ex0ScannedAllUnknown(ThCalculationNCCNeverTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test01_Th0Ex0ScannedAllUnknown -->
  <testcase name="test07_Th0Ex10Scanned9KnownWithMissingAndExtra" time="8.281" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test17_Th20Ex10Scanned10Unknown10Known" time="7.684" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test12_Th100Ex10Scanned8Known" time="8.060" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test14_Th100Ex10Scanned9KnownWithMissingAndExtra" time="8.670" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test05_Th0Ex10Scanned8Known" time="9.060" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test04_Th0Ex10Scanned10Known" time="8.767" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test09_Th100Ex0Scanned10Known" time="7.859" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
  <testcase name="test15_Th20Ex0ScannedAllUnknown" time="8.139" classname="com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest"/>
</testsuite> <!-- com.oatsystems.test.mv.ccthreshold.ThCalculationNCCNeverTest -->
