<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBANGNBLENO10" name="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest" tests="8" failures="3" timestamp="23 Oct 2018 20:35:25 GMT" time="153.704" errors="0">
  <testcase name="test07_Retirement" time="12.735" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B95C00000041D, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B95C00000041D, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:318)
at com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest.test07_Retirement(MF02_MultipleSequentialMsgTest.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test07_Retirement -->
  <testcase name="test06_EnterSoldItems" time="13.226" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest">
    <failure type="java.lang.AssertionError" message="Business location mismatch for the epc:3034186A940B95C000000414, Expected:null,Actual:StoreMFT1_ShippingArea">
      <![CDATA[java.lang.AssertionError: Business location mismatch for the epc:3034186A940B95C000000414, Expected:null,Actual:StoreMFT1_ShippingArea
at org.junit.Assert.fail(Assert.java:88)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifiyEPCInfo(MVHHMsgCommon.java:334)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:318)
at com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest.test06_EnterSoldItems(MF02_MultipleSequentialMsgTest.java:126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test06_EnterSoldItems -->
  <testcase name="test02_ReceivingTagged" time="13.126" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest"/>
  <testcase name="test03_PutAway" time="14.585" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest"/>
  <testcase name="test05_FilteredCycleCountNonStream" time="15.424" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest"/>
  <testcase name="test08_EncodeItems" time="49.180" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest">
    <failure type="java.lang.AssertionError" message="Message processing is not completed.">
      <![CDATA[java.lang.AssertionError: Message processing is not completed.
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at com.oatsystems.test.mv.hhmsgs.MVHHMsgCommon.verifyData(MVHHMsgCommon.java:315)
at com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest.test08_EncodeItems(MF02_MultipleSequentialMsgTest.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test08_EncodeItems -->
  <testcase name="test01_ReceivingUnTagged" time="16.790" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest"/>
  <testcase name="test04_CycleCountNonStream" time="18.638" classname="com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest"/>
</testsuite> <!-- com.oatsystems.test.mv.hhmsgs.MF02_MultipleSequentialMsgTest -->
