<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INBANGNBLENO10" name="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid" tests="4" failures="0" timestamp="31 Oct 2018 04:46:50 GMT" time="181.180" errors="0">
  <testcase name="Test04ReceiveRetireThenRetireAtSameLocation" time="48.716" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test01ReceiveRetireThenCycleCountAtSameLocation" time="44.500" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test02ReceiveRetireThenPutawayAtSameLocation" time="43.377" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
  <testcase name="Test03ReceiveRetireThenReturnAtSameLocation" time="44.587" classname="com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid"/>
</testsuite> <!-- com.chkpoint.jaytest1.Inventory_Test_UnknownInvalid -->
